#============================================================================
#
# Copyright (C) 2026 Ivan Pinezhaninov <ivan.pinezhaninov@gmail.com>
#
# This file is part of the SQLon which can be found at
# https://github.com/IvanPinezhaninov/sqlon/.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
# THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#============================================================================

if(NOT DEFINED SQLON_COVERAGE_BINARY_DIR OR SQLON_COVERAGE_BINARY_DIR STREQUAL "")
  message(FATAL_ERROR "SQLON_COVERAGE_BINARY_DIR is required")
endif()

file(GLOB_RECURSE SQLON_COVERAGE_DATA "${SQLON_COVERAGE_BINARY_DIR}/*.gcda")

if(SQLON_COVERAGE_DATA)
  file(REMOVE ${SQLON_COVERAGE_DATA})
endif()
