#============================================================================
#
# Copyright (C) 2026 Ivan Pinezhaninov <ivan.pinezhaninov@gmail.com>
#
# This file is part of the SQLon which can be found at
# https://github.com/IvanPinezhaninov/sqlon/.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
# THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#============================================================================

set(CPACK_GENERATOR "TGZ;ZIP")

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  list(INSERT CPACK_GENERATOR 0 DEB RPM)
endif()

set(CPACK_PACKAGE_NAME "sqlon")
set(CPACK_PACKAGE_VENDOR "Ivan Pinezhaninov")
set(CPACK_PACKAGE_CONTACT "Ivan Pinezhaninov <ivan.pinezhaninov@gmail.com>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Type-safe SQL construction for C++17")
set(CPACK_PACKAGE_DESCRIPTION "SQLon is a lightweight, database-agnostic SQL query builder for C++17.")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/IvanPinezhaninov/sqlon")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_DIRECTORY "${CMAKE_BINARY_DIR}/packages")
set(CPACK_PACKAGE_CHECKSUM "SHA256")
set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")
set(CPACK_PACKAGE_RELOCATABLE OFF)
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")

if(CMAKE_STRIP)
  set(CPACK_STRIP_FILES ON)
endif()

set(CPACK_INSTALL_DEFAULT_DIRECTORY_PERMISSIONS
  OWNER_READ
  OWNER_WRITE
  OWNER_EXECUTE
  GROUP_READ
  GROUP_EXECUTE
  WORLD_READ
  WORLD_EXECUTE
)

set(CPACK_COMPONENTS_ALL Development)

if(BUILD_SHARED_LIBS)
  list(INSERT CPACK_COMPONENTS_ALL 0 Runtime)
endif()

set(SQLON_RUNTIME_PACKAGE_DESCRIPTION "SQLon shared library.")
set(SQLON_DEVELOPMENT_PACKAGE_DESCRIPTION "SQLon C++ headers and CMake integration files.")

set(CPACK_COMPONENT_RUNTIME_DESCRIPTION "${SQLON_RUNTIME_PACKAGE_DESCRIPTION}")
set(CPACK_COMPONENT_DEVELOPMENT_DESCRIPTION "${SQLON_DEVELOPMENT_PACKAGE_DESCRIPTION}")

set(SQLON_DEBIAN_RUNTIME_PACKAGE_NAME "libsqlon${PROJECT_VERSION_MAJOR}")

set(CPACK_DEB_COMPONENT_INSTALL ON)
set(CPACK_DEBIAN_PACKAGE_RELEASE "1")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_CONTACT}")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "${CPACK_PACKAGE_HOMEPAGE_URL}")
set(CPACK_DEBIAN_PACKAGE_SOURCE "sqlon")

set(CPACK_DEBIAN_RUNTIME_PACKAGE_NAME "${SQLON_DEBIAN_RUNTIME_PACKAGE_NAME}")
set(CPACK_DEBIAN_RUNTIME_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_RUNTIME_PACKAGE_SECTION "libs")
set(CPACK_DEBIAN_RUNTIME_PACKAGE_SHLIBDEPS ON)

set(CPACK_DEBIAN_DEVELOPMENT_PACKAGE_NAME "libsqlon-dev")
set(CPACK_DEBIAN_DEVELOPMENT_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_DEVELOPMENT_PACKAGE_SECTION "libdevel")

if(BUILD_SHARED_LIBS)
  set(CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS ON)
  set(CPACK_DEBIAN_DEVELOPMENT_PACKAGE_DEPENDS "${SQLON_DEBIAN_RUNTIME_PACKAGE_NAME} (= ${PROJECT_VERSION}-1)")
endif()

set(CPACK_RPM_COMPONENT_INSTALL ON)
set(CPACK_RPM_PACKAGE_RELEASE "1")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_URL "${CPACK_PACKAGE_HOMEPAGE_URL}")
set(CPACK_RPM_PACKAGE_DESCRIPTION "${CPACK_PACKAGE_DESCRIPTION}")

set(CPACK_RPM_RUNTIME_PACKAGE_NAME "sqlon")
set(CPACK_RPM_RUNTIME_FILE_NAME "RPM-DEFAULT")
set(CPACK_RPM_RUNTIME_PACKAGE_SUMMARY "SQLon shared library")
set(CPACK_RPM_RUNTIME_PACKAGE_GROUP "System Environment/Libraries")
set(CPACK_RPM_RUNTIME_PACKAGE_DESCRIPTION "${SQLON_RUNTIME_PACKAGE_DESCRIPTION}")

set(CPACK_RPM_DEVELOPMENT_PACKAGE_NAME "sqlon-devel")
set(CPACK_RPM_DEVELOPMENT_FILE_NAME "RPM-DEFAULT")
set(CPACK_RPM_DEVELOPMENT_PACKAGE_SUMMARY "SQLon development files")
set(CPACK_RPM_DEVELOPMENT_PACKAGE_GROUP "Development/Libraries")
set(CPACK_RPM_DEVELOPMENT_PACKAGE_DESCRIPTION "${SQLON_DEVELOPMENT_PACKAGE_DESCRIPTION}")

if(BUILD_SHARED_LIBS)
  set(CPACK_RPM_DEVELOPMENT_PACKAGE_REQUIRES "sqlon = ${PROJECT_VERSION}-1")
endif()

set(CPACK_ARCHIVE_COMPONENT_INSTALL OFF)

include(CPack)
